### ISSUE TITLE
about install model

### ISSUE THREAD

**Issue by lizhaohu** [tonyngjichun/SOLAR#12]
hi, when I install model with: wget -nc https://imperialcollegelondon.box.com/shared/static/fznpeayct6btel2og2wjjgvqw0ziqnk4.pth -O data/networks/resnet101-solar-best.pth
![2022-01-11 11-53-17屏幕截图](https://user-images.githubusercontent.com/15177738/148878482-fe660d07-9ce6-40f1-8894-b54b369a4210.png)
,
It seems that the link timed out。
Is there any other way to download the model?

thanks

**Comment by tonyngjichun** [comment]
Hi, thanks for opening the issue.
The link works fine on my side, it seems like the network you are connected to might have blocked access to box. Have you tried connecting to a VPN before using wget?

**Comment by lizhaohu** [comment]
> Hi, thanks for opening the issue. The link works fine on my side, it seems like the network you are connected to might have blocked access to box. Have you tried connecting to a VPN before using wget?

yes  I have use VPN, Maybe it's because of my network。Can you send the global model to my email？ 15120377@bjtu.edu.cn
