### ISSUE TITLE
Training in a custom dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [tonyngjichun/SOLAR#2]
How do I prepare/structure a custom dataset?

**Comment by tonyngjichun** [comment]
Hi, as you can see in readme, we are preparing the code necessary to download and pre-process the gl18 dataset. Sorry it is taking a bit longer than usual as we have to ensure that each and every download link is working, and the dataset is quite huge (1mil+ images). In the code, you will see how to form the database pickle file from landmark labels to suit the dataset class `TuplesBatchedDataset` in `solar_global.datasets.traindataset`. Thank you for your patience :)

**Comment by tonyngjichun** [comment]
Hi, as the data processing code has been uploaded, I'm closing this issue. Please open a new issue if you encounter specific issues with that. Thanks! :D

**Comment by hewumars** [comment]
Have you successfully trained with custom datasets? @Zumbalamambo

**Comment by CodeJjang** [comment]
hi @tonyngjichun, is the local solar training scheme equals the global one (just different dataset and arch setup)?
is there any chance to release the exact steps used to train the local solar system on UBC?
